/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Funções.Logistica;
import Neuronio.Instancias;
import Neuronio.RedeNeural;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mortz
 */
public class Janela extends javax.swing.JFrame {
    private Instancias treinamento;
    private Instancias teste;
    private RedeNeural rede;
    
    private int numNeuroniosEntrada;
    private int numNeuroniosSaida;
    private int numNeuroniosOcultos;
    
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Abrir");

        jMenuItem1.setText("Conjunto de Treinamento");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Conjunto de Testes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Separar Conjunto de teste do conjunto de treinamento");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Rede Neural");

        jMenuItem2.setText("treinar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("teste");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("k-cross validation");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser j = new JFileChooser();
        if(j.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File arquivo = j.getSelectedFile();
            treinamento = new Instancias();
            treinamento.abrirArquivo(arquivo);
            treinamento.embaralhar();
            numNeuroniosEntrada = treinamento.getInstancia(0).atributos.length;
            numNeuroniosSaida = treinamento.getNumClasses();
            numNeuroniosOcultos = (int)Math.round(Math.sqrt(numNeuroniosEntrada * numNeuroniosSaida));
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        rede = new RedeNeural(numNeuroniosEntrada,numNeuroniosOcultos,3,numNeuroniosSaida,new Logistica());
        treinamento.normalizar(Instancias.NORMALIZAR_ENTRE_0E1);
        rede.treinamento(treinamento);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser j = new JFileChooser();
        if(j.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File arquivo = j.getSelectedFile();
            teste = new Instancias();
            teste.abrirArquivo(arquivo);
            teste.normalizar(Instancias.NORMALIZAR_ENTRE_0E1);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int[][] matriz = rede.testarRede(teste);
        for(int i=0;i<matriz.length;i++){
            for(int j=0;j<matriz[i].length;j++){
                System.out.print(matriz[i][j] + " ");
            }
            System.out.println(" ");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        double porcentagem = Double.valueOf(JOptionPane.showInputDialog("Porcentagem: "));
        teste = treinamento.separarTeste(porcentagem);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        int k = Integer.valueOf(JOptionPane.showInputDialog("k: "));
        int numClasses = treinamento.getNumClasses();
        int[][] acumulada = new int[numClasses][numClasses];
        treinamento.normalizar(Instancias.NORMALIZAR_ENTRE_0E1);
        for(int i=0;i<numClasses;i++){
            for(int j=0;j<numClasses;j++){
                acumulada[i][j] = 0;
            }
        }
        for(int i=0;i<k;i++){
            Instancias[] kfold = treinamento.kfold(i,k);
            RedeNeural r = new RedeNeural(numNeuroniosEntrada, numNeuroniosOcultos, 5, numNeuroniosSaida, new Logistica());
            r.treinamento(kfold[0]);
            int[][] resultado = r.testarRede(kfold[1]);
            for(int j=0;j<numClasses;j++){
                for(int l=0;l<numClasses;l++){
                    acumulada[j][l] += resultado[j][l];
                }
            }
        }
        for(int i=0;i<numClasses;i++){
            for(int j=0;j<numClasses;j++){
                System.out.print(acumulada[i][j] + "\t");
            }
            System.out.println("");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    
    public static void main(String[] args){
        Janela j = new Janela();
        j.toFront();
        j.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
